# Generated by Django 5.1.4 on 2025-01-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nic', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('resident', models.CharField(max_length=50)),
            ],
        ),
    ]
