# Generated by Django 5.1.4 on 2025-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='banner',
            field=models.ImageField(blank=True, default='student.jpg', upload_to=''),
        ),
    ]
